version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.59
    - 1.16.63
    - 1.17.22
    - 1.17.3
    - 1.17.44
    - 1.17.49
    - 1.17.7
  - dependency-name: moto
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.0.4
